Repository Zhi-704/Railway-Tracker, pull requests merged in 2024-07, with the labels that each got.

#3 add .gitignore
  .gitignore
Labels: Initial Setup

#5 Add requirements file
  requirements.txt
Labels: Setup

#6 Add GitHub actions
  .github/badges/avg_score.svg
  .github/badges/number_of_tests.svg
  .github/badges/passed_percentage.svg
  .github/workflows/main.yaml
  .util/parse_raw_python.py
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.json
  .util/pytest_scores.txt
  README.md
  requirements.txt
  test_file.py
Labels: Setup

#10 Api
  .gitignore
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  README.md
  national_rail/README.md
  national_rail/extract.py
  national_rail/requirements.txt
  realtime_trains/README.md
  realtime_trains/extract.py
  realtime_trains/requirements.txt
Labels: Documentation, Pipeline

#15 refactored extract file
  realtime_trains/extract.py
Labels: Pipeline, Polishing

#17 refactor national rail extract
  national_rail/extract.py
Labels: Pipeline

#19 fixed README files
  README.md
  national_rail/README.md
  national_rail/extract.py
  realtime_trains/README.md
Labels: Bug

#20 Create terraform RDS
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: Pipeline

#33 created schema and query file
  README.md
  database/README.md
  database/clear.sh
  database/query.sh
  database/query.sql
  database/schema.sql
  diagrams/ERD.png
  terraform/main.tf
Labels: Pipeline

#39 Dashboard config
  .util/pylint_scores.txt
  dashboard/.streamlit/config.toml
  dashboard/main_page.py
  dashboard/requirements.txt
Labels: Dashboard

#44 Add transform to realtimetrains folder
  .util/pylint_scores.txt
  realtime_trains/README.md
  realtime_trains/extract.py
  realtime_trains/transform.py
Labels: Pipeline, Performance

#46 fixed extract docstrings
  national_rail/extract.py
  realtime_trains/extract.py
Labels: Documentation, Pipeline, Incident, Performance

#45 Transform nationalrail
  .util/pylint_scores.txt
  national_rail/README.md
  national_rail/extract.py
  national_rail/requirements.txt
  national_rail/transform.py
Labels: Pipeline, Incident

#48 Test transform of NationalRail data
  .github/badges/number_of_tests.svg
  .gitignore
  .util/pytest_scores.json
  .util/pytest_scores.txt
  national_rail/test_data.xml
  national_rail/test_transform.py
  national_rail/transform.py
Labels: Pipeline, Testing

#47 seeded operators and cancel codes
  .util/pytest_scores.txt
  database/schema.sql
Labels: Pipeline

#52 Seed
  database/schema.sql
Labels: Pipeline

#53 updated schema
  database/schema.sql
  diagrams/ERD.png
Labels: Pipeline

#54 Load national rail
  .github/badges/avg_score.svg
  .util/pylint_scores.json
  .util/pylint_scores.txt
  database/query.sql
  national_rail/README.md
  national_rail/load.py
  national_rail/national_rail.py
  national_rail/requirements.txt
  national_rail/transform.py
Labels: Pipeline, Incident

#57 Updates schema and removed badges
  .github/workflows/main.yaml
  database/schema.sql
  diagrams/ERD.png
Labels: Bug

#65 Changed and updated schema to more appropriate data types
  database/schema.sql
Labels: Bug, Documentation

#60 Test Load for NationalRail
  .util/pytest_scores.json
  .util/pytest_scores.txt
  national_rail/test_load.py
  national_rail/test_transform.py
Labels: Incident, Testing

#66 Add load and realtime pipeline folder.
  .util/pylint_scores.json
  .util/pylint_scores.txt
  realtime_trains/extract.py
  realtime_trains/load.py
  realtime_trains/realtime_trains.py
  realtime_trains/requirements.txt
  realtime_trains/transform.py
Labels: Pipeline, Polishing, Performance

#61 Archive Incidents and waypoints
  .util/pylint_scores.json
  .util/pylint_scores.txt
  archive/DOCKERFILE
  archive/README.md
  archive/archive.py
  archive/clean_national_rail.py
  archive/clean_real_time_trains.py
  archive/db_connection.py
  archive/requirments.txt
  database/insert.sh
  database/insert.sql
  database/query.sql
  database/schema.sql
  national_rail/README.md
Labels: Archive

#63 Terraform archive
  archive/requirements.txt
  terraform/main.tf
Labels: Archive

#67 Add test pipeline
  .util/pylint_scores.txt
  .util/pytest_scores.json
  .util/pytest_scores.txt
  realtime_trains/extract_real.py
  realtime_trains/load_real.py
  realtime_trains/realtime_trains.py
  realtime_trains/test_extract_real.py
  realtime_trains/test_load_real.py
  realtime_trains/test_transform_real.py
  realtime_trains/transform_real.py
Labels: Pipeline, Performance, Testing

#69 Rename nationalrail files
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  national_rail/extract_national.py
  national_rail/load_national.py
  national_rail/national_rail.py
  national_rail/test_load_national.py
  national_rail/test_transform_national.py
  national_rail/transform_national.py
Labels: Polishing, Incident

#71 Add pipeline docker
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  realtime_trains/dockerfile
  realtime_trains/extract_real.py
  realtime_trains/load_real.py
  realtime_trains/realtime_trains.py
  realtime_trains/requirements.txt
  realtime_trains/transform_real.py
Labels: Pipeline, Performance, Deployment

#80 Terraform s3 bucket for reports
  .util/pytest_scores.txt
  terraform/main.tf
Labels: Report, Deployment

#82 Logging no incidents found
  .util/pytest_scores.txt
  national_rail/national_rail.py
Labels: Pipeline, Polishing, Incident

#77 Dashboard summary page
  .util/pylint_scores.json
  .util/pylint_scores.txt
  dashboard/pages/daily_report.py
Labels: Dashboard

#83 Extract PDF
  .util/pylint_scores.json
  .util/pylint_scores.txt
  pdf_report/Dockerfile
  pdf_report/README.md
  pdf_report/extract_pdf.py
  pdf_report/load_pdf.py
  pdf_report/requirements.txt
  pdf_report/test_extract_pdf.py
  pdf_report/test_load_pdf.py
  pdf_report/test_transform_pdf.py
  pdf_report/transform_pdf.py
Labels: Pipeline, Report

#88 Fix pipeline
  .util/pylint_scores.txt
  realtime_trains/transform_real.py
Labels: Bug, Pipeline, Performance

#92 Add notification to pipeline
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  national_rail/national_rail.py
  national_rail/requirements.txt
  national_rail/sns_reporting.py
Labels: Pipeline, Performance

#95 Added missing docstring, polished pylint, deleted unecessary functions
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  national_rail/sns_reporting.py
Labels: Pipeline, Polishing

#96 Dockerise national rail
  .util/pylint_scores.json
  .util/pylint_scores.txt
  national_rail/dockerfile
  national_rail/extract_national.py
  national_rail/national_rail.py
Labels: Pipeline, Incident, Deployment

#93 Terraform realtime etl
  .util/pytest_scores.txt
  database/query.sql
  realtime_trains/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: Performance, Deployment

#97 Terraform dashboard
  .util/pytest_scores.txt
  archive/README.md
  dashboard/README.md
  dashboard/dockerfile
  terraform/README.md
  terraform/main.tf
Labels: Dashboard, Deployment

#84 Transform PDF
  .gitignore
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.json
  .util/pytest_scores.txt
  database/query.sql
  pdf_report/extract_pdf.py
  pdf_report/pdf_report.py
  pdf_report/report.pdf
  pdf_report/requirements.txt
  pdf_report/styles.css
  pdf_report/transform_pdf.py
  realtime_trains/extract_real.py
  realtime_trains/realtime_trains.py
  test_file.py
Labels: Pipeline, Report

#100 Load report to s3
  .gitignore
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.json
  .util/pytest_scores.txt
  pdf_report/README.md
  pdf_report/load_pdf.py
  pdf_report/requirements.txt
  pdf_report/test_load_pdf.py
Labels: Report, Testing

#109 Update read me
  .util/pytest_scores.txt
  README.md
  national_rail/README.md
  realtime_trains/README.md
Labels: Documentation, Polishing

#110 PDF Report pipeline
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  pdf_report/Dockerfile
  pdf_report/README.md
  pdf_report/extract_pdf.py
  pdf_report/load_pdf.py
  pdf_report/pdf_report.py
  pdf_report/requirements.txt
  pdf_report/test_extract_pdf.py
  pdf_report/test_load_pdf.py
  pdf_report/transform_pdf.py
  realtime_trains/README.md
  terraform/README.md
  terraform/main.tf
Labels: Pipeline, Report

#98 Dashboard alerts page
  .github/badges/avg_score.svg
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  dashboard/pages/daily_report.py
  dashboard/pages/incident_alerts.py
Labels: Dashboard, Incident

#111 terraformed incident lambda and eventbridge
  .util/pytest_scores.txt
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: Pipeline, Incident, Deployment

#112 Test archive
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.json
  .util/pytest_scores.txt
  archive/clean_real_time_trains.py
  archive/db_connection.py
  archive/test_archive.py
  database/query.sql
  national_rail/load_national.py
  national_rail/national_rail.py
  national_rail/sns_reporting.py
  pdf_report/test_extract_pdf.py
  realtime_trains/load_real.py
  realtime_trains/realtime_trains.py
Labels: Testing, Archive

#114 Terraform realtime
  .util/pytest_scores.txt
  terraform/main.tf
Labels: Bug, Performance, Deployment

#117 Fix workflow
  .github/badges/avg_score.svg
  .github/badges/number_of_tests.svg
  .github/workflows/main.yaml
Labels: Bug, Documentation, Testing

#118 Terraform archive and report
  .github/badges/avg_score.svg
  .util/pylint_scores.json
  .util/pylint_scores.txt
  .util/pytest_scores.txt
  archive/archive.py
  pdf_report/Dockerfile
  pdf_report/README.md
  pdf_report/load_pdf.py
  pdf_report/pdf_report.py
  pdf_report/test_extract_pdf.py
  pdf_report/test_load_pdf.py
  pdf_report/test_transform_pdf.py
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: Deployment
